<?php
if (empty($HTTP_REFERER) || empty($REQUEST_URI)) {

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <title>\n";
echo "      Erreur 404\n";
echo "    </title>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <link rel=\"icon\" type=\"image/x-icon\" href=\"img/favicon.ico\">\n";
echo "    <meta name=\"author\" content=\"http://radservebeer.free.fr\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap\" rel=\"stylesheet\">\n";
echo "    <style type=\"text/css\">\n";
echo "    body {\n";
echo "      background-color: #262626;\n";
echo "    }\n";
echo "    .c4 {\n";
echo "      margin: auto;\n";
echo "    }\n";
echo "    #centre {\n";
echo "      text-align: center;\n";
echo "    }\n";
echo "    p {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 1rem;\n";
echo "      color: #ccc;\n";
echo "    }\n";
echo "    h1 {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 6rem;\n";
echo "      font-weight: 700;\n";
echo "      color: rgba(7, 151, 195, .4);\n";
echo "      margin-top: -100px;\n";
echo "      margin: auto;\n";
echo "    }\n";
echo "    h2 {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 2rem;\n";
echo "      font-weight: 700;\n";
echo "      color: rgba(7, 151, 195, .2);\n";
echo "    }\n";
echo "    a:link {\n";
echo "      color: #ff8000;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    a:visited {\n";
echo "      color: #ff8000;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    a:hover {\n";
echo "      color: #f00;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    hr {\n";
echo "      width: 50%;\n";
echo "      height: 3px;\n";
echo "      background: rgba(7, 151, 195, .2);\n";
echo "      border: 0;\n";
echo "    }\n";
echo "    </style>\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "    <img src=\"img/images1.png\" style=\"margin-top: -7px; opacity: 0.5\" alt=\"\"><img src=\"img/images2.png\" style=\"float: right; margin-top: -7px; opacity: 0.5;\" alt=\"\">\n";
echo "    <div id=\"centre\">\n";
echo "      <h1>404</h1>\n";
echo "      <hr>\n";
echo "      <h2>La page demand&eacute;e est introuvable.\n";
echo "      </h2>\n";
echo "      <p>\n";
echo "        Le lien sur lequel vous venez de cliquer redirige vers une page inexistante.\n";
echo "        <br>\n";
echo "        <br>\n";
echo "        <a href=\".\">Retour &agrave; la page d'accueil du site</a>\n";
echo "      </p>\n";
echo "      <video class=\"c4\" muted=\"muted\" autoplay=\"autoplay\" poster=\"Exemple_ShowHide_+_SyntaxHighlighter/files/images/rz.jpg\" width=\"500\" height=\"210\" loop=\"loop\" onended=\"var v=this;setTimeout(function(){v.play()},300)\">\n";
echo "            <source src=\"Exemple_ShowHide_+_SyntaxHighlighter/files/media/rz_2.mp4\" type=\"video/mp4\">\n";
echo "          </video>\n";
echo "    </div>\n";
echo "  </body>\n";
echo "</html>";
} else {

    /* On recupere le nom du site */
    $site = $_SERVER["SERVER_NAME"];

    /* Si a bien cliquez sur un lien, mais un lien externe */
    if (!ereg($site, $_SERVER["HTTP_REFERER"])) {

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <title>\n";
echo "      Erreur 404\n";
echo "    </title>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <link rel=\"icon\" type=\"image/x-icon\" href=\"img/favicon.ico\">\n";
echo "    <meta name=\"author\" content=\"http://radservebeer.free.fr\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n";
echo "    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap\" rel=\"stylesheet\">\n";
echo "    <style type=\"text/css\">\n";
echo "    body {\n";
echo "      background-color: #262626;\n";
echo "    }\n";
echo "    .c4 {\n";
echo "      margin: auto;\n";
echo "    }\n";
echo "    #centre {\n";
echo "      text-align: center;\n";
echo "    }\n";
echo "    p {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 1rem;\n";
echo "      color: #ccc;\n";
echo "    }\n";
echo "    h1 {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 6rem;\n";
echo "      font-weight: 700;\n";
echo "      color: rgba(7, 151, 195, .4);\n";
echo "      margin-top: -100px;\n";
echo "      margin: auto;\n";
echo "    }\n";
echo "    h2 {\n";
echo "      font-family: Quicksand, 'Helvetica Neue', Arial, sans-serif;\n";
echo "      font-size: 2rem;\n";
echo "      font-weight: 700;\n";
echo "      color: rgba(7, 151, 195, .2);\n";
echo "    }\n";
echo "    a:link {\n";
echo "      color: #ff8000;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    a:visited {\n";
echo "      color: #ff8000;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    a:hover {\n";
echo "      color: #f00;\n";
echo "      text-decoration: none;\n";
echo "    }\n";
echo "    hr {\n";
echo "      width: 50%;\n";
echo "      height: 3px;\n";
echo "      background: rgba(7, 151, 195, .2);\n";
echo "      border: 0;\n";
echo "    }\n";
echo "    </style>\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "    <img src=\"img/images1.png\" style=\"margin-top: -7px; opacity: 0.5\" alt=\"\"><img src=\"img/images2.png\" style=\"float: right; margin-top: -7px; opacity: 0.5;\" alt=\"\">\n";
echo "    <div id=\"centre\">\n";
echo "      <h1>404</h1>\n";
echo "      <hr>\n";
echo "      <h2>La page demand&eacute;e est introuvable.\n";
echo "      </h2>\n";
echo "      <p>\n";
echo "        Le lien sur lequel vous venez de cliquer redirige vers une page inexistante.\n";
echo "        <br>\n";
echo "        <br>\n";
echo "        <a href=\".\">Retour &agrave; la page d'accueil du site</a>\n";
echo "      </p>\n";
echo "      <video class=\"c4\" muted=\"muted\" autoplay=\"autoplay\" poster=\"Exemple_ShowHide_+_SyntaxHighlighter/files/images/rz.jpg\" width=\"500\" height=\"210\" loop=\"loop\" onended=\"var v=this;setTimeout(function(){v.play()},300)\">\n";
echo "            <source src=\"Exemple_ShowHide_+_SyntaxHighlighter/files/media/rz_2.mp4\" type=\"video/mp4\">\n";
echo "          </video>\n";
echo "    </div>\n";
echo "  </body>\n";
echo "</html>";
 }
 else {
    echo "<!DOCTYPE html>\n";
    echo "<html>\n";
    echo "  <head>\n";
    echo "    <title>\n";
    echo "      Erreur 404\n";
    echo "    </title>\n";
    echo "    <style type=\"text/css\">\n";
    echo "    div.c5 {\n";
    echo "        margin: 0 auto;\n";
    echo "        padding: 30px 10px;\n";
    echo "        position: relative;\n";
    echo "        width: 600px;\n";
    echo "      }\n";
    echo "\n";
    echo "      div.c4 {\n";
    echo "        position: relative;\n";
    echo "        width: 600px;\n";
    echo "        height: 252px;\n";
    echo "        background: url(/error/rz.png)}\n";
    echo "    object.c3 {\n";
    echo "          position:relative;\n";
    echo "        }\n";
    echo "        img.c2 {\n";
    echo "          position: absolute;\n";
    echo "          left: 0;\n";
    echo "        }\n";
    echo "        embed.c1 {\n";
    echo "          position: relative;\n";
    echo "        }\n";
    echo "    body {\n";
    echo "        background-color: #262626;\n";
    echo "      }\n";
    echo "\n";
    echo "      p {\n";
    echo "        font-family: Verdana, Arial, Helvetica, sans-serif;\n";
    echo "        font-size: 100%;\n";
    echo "        color: #CCCCCC;\n";
    echo "        text-align: center;\n";
    echo "      }\n";
    echo "\n";
    echo "      h2 {\n";
    echo "        font-family: Verdana, Helvetica, Arial, sans-serif;\n";
    echo "        font-size: 160%;\n";
    echo "        color: #709c47;\n";
    echo "        text-align: center;\n";
    echo "        font-weight: bold;\n";
    echo "      }\n";
    echo "\n";
    echo "      a:link {\n";
    echo "        color: #FF8000;\n";
    echo "        text-decoration: none;\n";
    echo "      }\n";
    echo "\n";
    echo "      a:visited {\n";
    echo "        color: #FF8000;\n";
    echo "        text-decoration: none;\n";
    echo "      }\n";
    echo "\n";
    echo "      a:hover {\n";
    echo "        color: #FF0000;\n";
    echo "        text-decoration: none;\n";
    echo "      }\n";
    echo "   </style>\n";
    echo "  </head>\n";
    echo "  <body>\n";
    echo "    <img src=\"http://radservebeer.free.fr/error/images1.png\" style=\"margin-top: -7px; opacity: 0.5\" alt=\"\"><img src=\"http://radservebeer.free.fr/error/images2.png\"  style=\"float: right; margin-top: -7px; opacity: 0.5;\" alt=\"\">\n";
    echo "    <h2>\n";
    echo "      Erreur 404 : La page demand&eacute;e est introuvable.\n";
    echo "    </h2>\n";
    echo "    <p>\n";
    echo "      Le lien sur lequel vous venez de cliquer redirige vers une page inexistante.\n";
    echo "      <br>\n";
    echo "      <br>\n";
    echo "      <a href=\"/\">Retour &agrave; la page d'accueil du site</a>\n";
    echo "    </p>\n";
    echo "    <div align=\"center\">\n";
    echo "      <div class=\"c5\">\n";
    echo "        <div class=\"c4\">\n";
    echo "          <video muted=\"muted\" autoplay=\"autoplay\" poster=\"http://radservebeer.free.fr/error/rz.files/rz.png\" width=\"600\" height=\"252\" loop=\"loop\"\n";
    echo "          onended=\"var v=this;setTimeout(function(){v.play()},300)\"><source src=\"http://radservebeer.free.fr/error/rz.files/rz.mp4\" type=\"video/mp4\">\n";
    echo "          <source src=\"http://radservebeer.free.fr/error/rz.files/rz.webm\" type=\"video/webm\"> </video>\n";
    echo "        </div>\n";
    echo "      </div>\n";
    echo "    </div>\n";
    echo "  </body>\n";
    echo "</html>\n";
  }}

 ?>