if(!window.SyntaxHighlighter)var SyntaxHighlighter=function(){var e={defaults:{"class-name":"","first-line":1,"pad-line-numbers":!0,highlight:null,"smart-tabs":!0,"tab-size":4,gutter:!0,toolbar:!0,collapse:!0,"auto-links":!0,light:!1,
"wrap-lines":!0,"html-script":!1},config:{useScriptTags:!0,clipboardSwf:null,toolbarItemWidth:16,toolbarItemHeight:16,bloggerMode:!1,stripBrs:!1,tagName:"pre",strings:{expandSource:"show source",viewSource:"view source",
copyToClipboard:"copy to clipboard",copyToClipboardConfirmation:"The code is in your clipboard now",print:"print",help:"?",alert:"SyntaxHighlighter\n\n",noBrush:"Can't find brush for: ",
brushNotHtmlScript:"Brush wasn't configured for html-script option: ",aboutDialog:"RADZONE"},debug:!1},vars:{discoveredBrushes:null,spaceWidth:null,printFrame:null,highlighters:{}},brushes:{},regexLib:{
multiLineCComments:/\/\*[\s\S]*?\*\//gm,singleLineCComments:/\/\/.*$/gm,singleLinePerlComments:/#.*$/gm,doubleQuotedString:/"([^\\"\n]|\\.)*"/g,singleQuotedString:/'([^\\'\n]|\\.)*'/g,multiLineDoubleQuotedString:/"([^\\"]|\\.)*"/g,
multiLineSingleQuotedString:/'([^\\']|\\.)*'/g,xmlComments:/(&lt;|<)!--[\s\S]*?--(&gt;|>)/gm,url:/&lt;\w+:\/\/[\w-.\/?%&=@:;]*&gt;|\w+:\/\/[\w-.\/?%&=@:;]*/g,phpScriptTags:{left:/(&lt;|<)\?=?/g,right:/\?(&gt;|>)/g},aspScriptTags:{
left:/(&lt;|<)%=?/g,right:/%(&gt;|>)/g},scriptScriptTags:{left:/(&lt;|<)\s*script.*?(&gt;|>)/gi,right:/(&lt;|<)\/\s*script\s*(&gt;|>)/gi}},toolbar:{create:function(t){var n=document.createElement("DIV"),i=e.toolbar.items
;for(var r in n.className="toolbar",i){var s=new(0,i[r])(t),a=s.create();t.toolbarCommands[r]=s,null!=a&&("string"==typeof a&&(a=e.toolbar.createButton(a,t.id,r)),a.className+="item "+r,n.appendChild(a))}return n},
createButton:function(t,n,i){var r=document.createElement("a"),s=r.style,a=e.config,l=a.toolbarItemWidth,c=a.toolbarItemHeight;return r.href="#"+i,r.title=t,r.highlighterId=n,r.commandName=i,r.innerHTML=t,0==isNaN(l)&&(s.width=l+"px"),
0==isNaN(c)&&(s.height=c+"px"),r.onclick=function(t){try{e.toolbar.executeCommand(this,t||window.event,this.highlighterId,this.commandName)}catch(t){e.utils.alert(t.message)}return!1},r},executeCommand:function(t,n,i,r,s){
var a,l=e.vars.highlighters[i];return null==l||null==(a=l.toolbarCommands[r])?null:a.execute(t,n,s)},items:{expandSource:function(t){this.create=function(){if(1==t.getParam("collapse"))return e.config.strings.expandSource},
this.execute=function(e,n,i){var r=t.div;e.parentNode.removeChild(e),r.className=r.className.replace("collapsed","")}},viewSource:function(t){this.create=function(){return e.config.strings.viewSource},this.execute=function(n,i,r){
var s=e.utils.fixInputString(t.originalCode).replace(/</g,"&lt;"),a=e.utils.popup("","_blank",750,400,"location=0, resizable=1, menubar=0, scrollbars=1");s=e.utils.unindent(s),a.document.write("<pre>"+s+"</pre>"),a.document.close()}},
copyToClipboard:function(t){var n,i=t.id;this.create=function(){var t=e.config;if(null==t.clipboardSwf)return null;function r(e){var t="";for(var n in e)t+="<param name='"+n+"' value='"+e[n]+"'/>";return t}function s(e){var t=""
;for(var n in e)t+=" "+n+"='"+e[n]+"'";return t}var a,l={width:t.toolbarItemWidth,height:t.toolbarItemHeight,id:i+"_clipboard",type:"application/x-shockwave-flash",title:e.config.strings.copyToClipboard},c={allowScriptAccess:"always",
wmode:"transparent",flashVars:"highlighterId="+i,menu:"false"},o=t.clipboardSwf;return a=/msie/i.test(navigator.userAgent)?"<object"+s({classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",
codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"})+s(l)+">"+r(c)+r({movie:o})+"</object>":"<embed"+s(l)+s(c)+s({src:o})+"/>",(n=document.createElement("div")).innerHTML=a,n},
this.execute=function(n,i,r){switch(r.command){case"get":var s=e.utils.unindent(e.utils.fixInputString(t.originalCode).replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&"));if(!window.clipboardData)return e.utils.unindent(s)
;window.clipboardData.setData("text",s);case"ok":e.utils.alert(e.config.strings.copyToClipboardConfirmation);break;case"error":e.utils.alert(r.message)}}},printSource:function(t){this.create=function(){return e.config.strings.print},
this.execute=function(n,i,r){var s=document.createElement("IFRAME"),a=null;null!=e.vars.printFrame&&document.body.removeChild(e.vars.printFrame),e.vars.printFrame=s,
s.style.cssText="position:absolute;width:0px;height:0px;left:-500px;top:-500px;",document.body.appendChild(s),function(e,t){
for(var n=t.getElementsByTagName("link"),i=0;i<n.length;i++)"stylesheet"==n[i].rel.toLowerCase()&&/shCore\.css$/.test(n[i].href)&&e.write('<link type="text/css" rel="stylesheet" href="'+n[i].href+'"></link>')
}(a=s.contentWindow.document,window.document),a.write('<div class="'+t.div.className.replace("collapsed","")+' printing">'+t.div.innerHTML+"</div>"),a.close(),s.contentWindow.focus(),s.contentWindow.print()}},about:function(t){
this.create=function(){return e.config.strings.help},this.execute=function(t,n){var i=e.utils.popup("","_blank",500,250,"scrollbars=0"),r=i.document;r.write(e.config.strings.aboutDialog),r.close(),i.focus()}}}},utils:{
indexOf:function(e,t,n){for(var i=n=Math.max(n||0,0);i<e.length;i++)if(e[i]==t)return i;return-1},guid:function(e){return e+Math.round(1e6*Math.random()).toString()},merge:function(e,t){var n,i={};for(n in e)i[n]=e[n];for(n in t)i[n]=t[n]
;return i},toBoolean:function(e){switch(e){case"true":return!0;case"false":return!1}return e},popup:function(e,t,n,i,r){r=(r+=", left="+(screen.width-n)/2+", top="+(screen.height-i)/2+", width="+n+", height="+i).replace(/^,/,"")
;var s=window.open(e,t,r);return s.focus(),s},addEvent:function(e,t,n){e.attachEvent?(e["e"+t+n]=n,e[t+n]=function(){e["e"+t+n](window.event)},e.attachEvent("on"+t,e[t+n])):e.addEventListener(t,n,!1)},alert:function(t){
alert(e.config.strings.alert+t)},findBrush:function(t,n){var i,r=e.vars.discoveredBrushes;if(null==r){for(var s in r={},e.brushes){var a=e.brushes[s].aliases;if(null!=a){e.brushes[s].name=s.toLowerCase();for(var l=0;l<a.length;l++)r[a[l]]=s
}}e.vars.discoveredBrushes=r}return null==(i=e.brushes[r[t]])&&0!=n&&e.utils.alert(e.config.strings.noBrush+t),i},eachLine:function(e,t){for(var n=e.split("\n"),i=0;i<n.length;i++)n[i]=t(n[i]);return n.join("\n")},
trimFirstAndLastLines:function(e){return e.replace(/^[ ]*[\n]+|[\n]*[ ]*$/g,"")},parseParams:function(e){
for(var t,n={},i=new XRegExp("^\\[(?<values>(.*?))\\]$"),r=new XRegExp("(?<name>[\\w-]+)\\s*:\\s*(?<value>[\\w-%#]+|\\[.*?\\]|\".*?\"|'.*?')\\s*;?","g");null!=(t=r.exec(e));){var s=t.value.replace(/^['"]|['"]$/g,"");if(null!=s&&i.test(s)){
var a=i.exec(s);s=a.values.length>0?a.values.split(/\s*,\s*/):[]}n[t.name]=s}return n},decorate:function(t,n){return null==t||0==t.length||"\n"==t?t:(t=(t=t.replace(/</g,"&lt;")).replace(/ {2,}/g,function(e){
for(var t="",n=0;n<e.length-1;n++)t+="&nbsp;";return t+" "}),null!=n&&(t=e.utils.eachLine(t,function(e){if(0==e.length)return"";var t="";return 0==(e=e.replace(/^(&nbsp;| )+/,function(e){return t=e,""
})).length?t:t+'<code class="'+n+'">'+e+"</code>"})),t)},padNumber:function(e,t){for(var n=e.toString();n.length<t;)n="0"+n;return n},measureSpace:function(){
var t,n=document.createElement("div"),i=0,r=document.body,s=e.utils.guid("measureSpace"),a='<div class="'
;if(n.innerHTML=a+'syntaxhighlighter">'+a+'lines">'+a+'line">'+a+'content"><span class="block"><span id="'+s+'">&nbsp;</span></span></div></div></div></div>',r.appendChild(n),t=document.getElementById(s),/opera/i.test(navigator.userAgent)){
var l=window.getComputedStyle(t,null);i=parseInt(l.getPropertyValue("width"))}else i=t.offsetWidth;return r.removeChild(n),i},processTabs:function(e,t){for(var n="",i=0;i<t;i++)n+=" ";return e.replace(/\t/g,n)},
processSmartTabs:function(t,n){t.split("\n");for(var i="",r=0;r<50;r++)i+="                    ";function s(e,t,n){return e.substr(0,t)+i.substr(0,n)+e.substr(t+1,e.length)}return t=e.utils.eachLine(t,function(e){
if(-1==e.indexOf("\t"))return e;for(var t=0;-1!=(t=e.indexOf("\t"));){e=s(e,t,n-t%n)}return e})},fixInputString:function(t){var n=/<br\s*\/?>|&lt;br\s*\/?&gt;/gi;return 1==e.config.bloggerMode&&(t=t.replace(n,"\n")),
1==e.config.stripBrs&&(t=t.replace(n,"")),t},trim:function(e){return e.replace(/^\s+|\s+$/g,"")},unindent:function(t){for(var n=e.utils.fixInputString(t).split("\n"),i=(new Array,/^\s*/),r=1e3,s=0;s<n.length&&r>0;s++){var a=n[s]
;if(0!=e.utils.trim(a).length){var l=i.exec(a);if(null==l)return t;r=Math.min(l[0].length,r)}}if(r>0)for(s=0;s<n.length;s++)n[s]=n[s].substr(r);return n.join("\n")},matchesSortCallback:function(e,t){
return e.index<t.index?-1:e.index>t.index?1:e.length<t.length?-1:e.length>t.length?1:0},getMatches:function(t,n){for(var i=null,r=[],s=n.func?n.func:function(t,n){return[new e.Match(t[0],t.index,n.css)]
};null!=(i=n.regex.exec(t));)r=r.concat(s(i,n));return r},processUrls:function(t){var n="&lt;",i="&gt;";return t.replace(e.regexLib.url,function(e){var t="",r="";return 0==e.indexOf(n)&&(r=n,e=e.substring(n.length)),
e.indexOf(i)==e.length-i.length&&(e=e.substring(0,e.length-i.length),t=i),r+'<a href="'+e+'">'+e+"</a>"+t})},getSyntaxHighlighterScriptTags:function(){
for(var e=document.getElementsByTagName("script"),t=[],n=0;n<e.length;n++)"syntaxhighlighter"==e[n].type&&t.push(e[n]);return t},stripCData:function(t){var n=e.utils.trim(t),i=!1
;return 0==n.indexOf("<![CDATA[")&&(n=n.substring("<![CDATA[".length),i=!0),n.indexOf("]]>")==n.length-"]]>".length&&(n=n.substring(0,n.length-"]]>".length),i=!0),i?n:t}},highlight:function(t,n){var i=n?[n]:function(e){
for(var t=[],n=0;n<e.length;n++)t.push(e[n]);return t}(document.getElementsByTagName(e.config.tagName)),r=null,s=e.config;if(s.useScriptTags&&(i=i.concat(e.utils.getSyntaxHighlighterScriptTags())),0!==i.length)for(var a=0;a<i.length;a++){
var l,c,o,u=i[a],h=e.utils.parseParams(u.className);if(null!=(l=(h=e.utils.merge(t,h)).brush)){if("true"==h["html-script"]||1==e.defaults["html-script"])r=new e.HtmlScript(l),l="htmlscript";else{var g=e.utils.findBrush(l);if(!g)continue
;l=g.name,r=new g}c=u.innerHTML,s.useScriptTags&&(c=e.utils.stripCData(c)),h["brush-name"]=l,r.highlight(c,h),o=r.div,e.config.debug&&((o=document.createElement("textarea")).value=r.div.innerHTML,o.style.width="70em",o.style.height="30em"),
u.parentNode.replaceChild(o,u)}}},all:function(t){e.utils.addEvent(window,"load",function(){e.highlight(t)})},Match:function(e,t,n){this.value=e,this.index=t,this.length=e.length,this.css=n,this.brushName=null}}
;return e.Match.prototype.toString=function(){return this.value},e.HtmlScript=function(t){var n,i=e.utils.findBrush(t),r=new e.brushes.Xml;function s(e,t){for(var n=0;n<e.length;n++)e[n].index+=t}null!=i&&(n=new i,this.xmlBrush=r,
null!=n.htmlScript?r.regexList.push({regex:n.htmlScript.code,func:function(t,r){for(var a,l=t.code,c=[],o=n.regexList,u=t.index+t.left.length,h=n.htmlScript,g=0;g<o.length;g++)s(a=e.utils.getMatches(l,o[g]),u),c=c.concat(a)
;null!=h.left&&null!=t.left&&(s(a=e.utils.getMatches(t.left,h.left),t.index),c=c.concat(a));null!=h.right&&null!=t.right&&(s(a=e.utils.getMatches(t.right,h.right),t.index+t[0].lastIndexOf(t.right)),c=c.concat(a))
;for(var p=0;p<c.length;p++)c[p].brushName=i.name;return c}}):e.utils.alert(e.config.strings.brushNotHtmlScript+t))},e.HtmlScript.prototype.highlight=function(e,t){this.xmlBrush.highlight(e,t),this.div=this.xmlBrush.div},
e.Highlighter=function(){},e.Highlighter.prototype={getParam:function(t,n){var i=this.params[t];return e.utils.toBoolean(null==i?n:i)},create:function(e){return document.createElement(e)},findMatches:function(t,n){var i=[]
;if(null!=t)for(var r=0;r<t.length;r++)"object"==typeof t[r]&&(i=i.concat(e.utils.getMatches(n,t[r])));return i.sort(e.utils.matchesSortCallback)},removeNestedMatches:function(){
for(var e=this.matches,t=0;t<e.length;t++)if(null!==e[t])for(var n=e[t],i=n.index+n.length,r=t+1;r<e.length&&null!==e[t];r++){var s=e[r];if(null!==s){if(s.index>i)break
;s.index==n.index&&s.length>n.length?this.matches[t]=null:s.index>=n.index&&s.index<i&&(this.matches[r]=null)}}},createDisplayLines:function(t){
var n=t.split(/\n/g),i=parseInt(this.getParam("first-line")),r=this.getParam("pad-line-numbers"),s=this.getParam("highlight",[]),a=this.getParam("gutter");t="",1==r?r=(i+n.length-1).toString().length:1==isNaN(r)&&(r=0)
;for(var l=0;l<n.length;l++){var c=n[l],o=/^(&nbsp;|\s)+/.exec(c),u="alt"+(l%2==0?1:2),h=e.utils.padNumber(i+l,r),g=-1!=e.utils.indexOf(s,(i+l).toString()),p=null;null!=o&&(p=o[0].toString(),c=c.substr(p.length)),
0==(c=e.utils.trim(c)).length&&(c="&nbsp;"),
g&&(u+=" highlighted"),t+='<div class="line '+u+'"><table><tr>'+(a?'<td class="number"><code>'+h+"</code></td>":"")+'<td class="content">'+(null!=p?'<code class="spaces">'+p.replace(" ","&nbsp;")+"</code>":"")+c+"</td></tr></table></div>"}
return t},processMatches:function(t,n){var i=0,r="",s=e.utils.decorate,a=this.getParam("brush-name","");function l(e){var t=e&&e.brushName||a;return t?t+" ":""}for(var c=0;c<n.length;c++){var o,u=n[c];null!==u&&0!==u.length&&(o=l(u),
r+=s(t.substr(i,u.index-i),o+"plain")+s(u.value,o+u.css),i=u.index+u.length)}return r+=s(t.substr(i),l()+"plain")},highlight:function(t,n){e.config;var i,r,s=e.vars;if(this.params={},this.div=null,this.lines=null,this.code=null,
this.bar=null,this.toolbarCommands={},this.id=e.utils.guid("highlighter_"),s.highlighters[this.id]=this,null===t&&(t=""),this.params=e.utils.merge(e.defaults,n||{}),1==this.getParam("light")&&(this.params.toolbar=this.params.gutter=!1),
this.div=i=this.create("DIV"),this.lines=this.create("DIV"),this.lines.className="lines",className="syntaxhighlighter",i.id=this.id,this.getParam("collapse")&&(className+=" collapsed"),0==this.getParam("gutter")&&(className+=" nogutter"),
0==this.getParam("wrap-lines")&&(this.lines.className+=" no-wrap"),className+=" "+this.getParam("class-name"),className+=" "+this.getParam("brush-name"),i.className=className,this.originalCode=t,
this.code=e.utils.trimFirstAndLastLines(t).replace(/\r/g," "),r=this.getParam("tab-size"),this.code=1==this.getParam("smart-tabs")?e.utils.processSmartTabs(this.code,r):e.utils.processTabs(this.code,r),this.code=e.utils.unindent(this.code),
this.getParam("toolbar")){this.bar=this.create("DIV"),this.bar.className="bar",this.bar.appendChild(e.toolbar.create(this)),i.appendChild(this.bar);var a=this.bar;function l(){a.className=a.className.replace("show","")}
i.onmouseover=function(){l(),a.className+=" show"},i.onmouseout=function(){l()}}i.appendChild(this.lines),this.matches=this.findMatches(this.regexList,this.code),this.removeNestedMatches(),t=this.processMatches(this.code,this.matches),
t=this.createDisplayLines(e.utils.trim(t)),this.getParam("auto-links")&&(t=e.utils.processUrls(t)),this.lines.innerHTML=t},getKeywords:function(e){return"\\b(?:"+(e=e.replace(/^\s+|\s+$/g,"").replace(/\s+/g,"|"))+")\\b"},
forHtmlScript:function(e){this.htmlScript={left:{regex:e.left,css:"script"},right:{regex:e.right,css:"script"},code:new XRegExp("(?<left>"+e.left.source+")(?<code>.*?)(?<right>"+e.right.source+")","sgi")}}},e}();window.XRegExp||function(){
var e={exec:RegExp.prototype.exec,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},t={
part:/(?:[^\\([#\s.]+|\\(?!k<[\w$]+>|[pP]{[^}]+})[\S\s]?|\((?=\?(?!#|<[\w$]+>)))+|(\()(?:\?(?:(#)[^)]*\)|<([$\w]+)>))?|\\(?:k<([\w$]+)>|[pP]{([^}]+)})|(\[\^?)|([\S\s])/g,
replaceVar:/(?:[^$]+|\$(?![1-9$&`']|{[$\w]+}))+|\$(?:([1-9]\d*|[$&`'])|{([$\w]+)})/g,extended:/^(?:\s+|#.*)+/,quantifier:/^(?:[?*+]|{\d+(?:,\d*)?})/,classLeft:/&&\[\^?/g,classRight:/]/g},n=function(e,t,n){
for(var i=n||0;i<e.length;i++)if(e[i]===t)return i;return-1},i=void 0!==/()??/.exec("")[1],r={};XRegExp=function(i,s){if(i instanceof RegExp){if(void 0!==s)throw TypeError("can't supply flags when constructing one RegExp from another")
;return i.addFlags()}var a,l,c,o,u,h=(s=s||"").indexOf("s")>-1,g=s.indexOf("x")>-1,p=!1,d=[],f=[],m=t.part;for(m.lastIndex=0;a=e.exec.call(m,i);)a[2]?t.quantifier.test(i.slice(m.lastIndex))||f.push("(?:)"):a[1]?(d.push(a[3]||null),
a[3]&&(p=!0),
f.push("(")):a[4]?(o=n(d,a[4]),f.push(o>-1?"\\"+(o+1)+(isNaN(i.charAt(m.lastIndex))?"":"(?:)"):a[0])):a[5]?f.push(r.unicode?r.unicode.get(a[5],"P"===a[0].charAt(1)):a[0]):a[6]?"]"===i.charAt(m.lastIndex)?(f.push("["===a[6]?"(?!)":"[\\S\\s]"),
m.lastIndex++):(l=XRegExp.matchRecursive("&&"+i.slice(a.index),t.classLeft,t.classRight,"",{escapeChar:"\\"})[0],f.push(a[6]+l+"]"),
m.lastIndex+=l.length+1):a[7]?h&&"."===a[7]?f.push("[\\S\\s]"):g&&t.extended.test(a[7])?(c=e.exec.call(t.extended,i.slice(m.lastIndex-1))[0].length,t.quantifier.test(i.slice(m.lastIndex-1+c))||f.push("(?:)"),
m.lastIndex+=c-1):f.push(a[7]):f.push(a[0]);return(u=RegExp(f.join(""),e.replace.call(s,/[sx]+/g,"")))._x={source:i,captureNames:p?d:null},u},XRegExp.addPlugin=function(e,t){r[e]=t},RegExp.prototype.exec=function(t){
var n,r,s,a=e.exec.call(this,t);if(a){if(i&&a.length>1&&(s=new RegExp("^"+this.source+"$(?!\\s)",this.getNativeFlags()),e.replace.call(a[0],s,function(){for(r=1;r<arguments.length-2;r++)void 0===arguments[r]&&(a[r]=void 0)})),
this._x&&this._x.captureNames)for(r=1;r<a.length;r++)(n=this._x.captureNames[r-1])&&(a[n]=a[r]);this.global&&this.lastIndex>a.index+a[0].length&&this.lastIndex--}return a}}(),RegExp.prototype.getNativeFlags=function(){
return(this.global?"g":"")+(this.ignoreCase?"i":"")+(this.multiline?"m":"")+(this.extended?"x":"")+(this.sticky?"y":"")},RegExp.prototype.addFlags=function(e){var t=new XRegExp(this.source,(e||"")+this.getNativeFlags())
;return this._x&&(t._x={source:this._x.source,captureNames:this._x.captureNames?this._x.captureNames.slice(0):null}),t},RegExp.prototype.call=function(e,t){return this.exec(t)},RegExp.prototype.apply=function(e,t){return this.exec(t[0])},
XRegExp.cache=function(e,t){var n="/"+e+"/"+(t||"");return XRegExp.cache[n]||(XRegExp.cache[n]=new XRegExp(e,t))},XRegExp.escape=function(e){return e.replace(/[-[\]{}()*+?.\\^$|,#\s]/g,"\\$&")},XRegExp.matchRecursive=function(e,t,n,i,r){
var s,a,l,c,o,u,h=(r=r||{}).escapeChar,g=r.valueNames,p=(i=i||"").indexOf("g")>-1,d=i.indexOf("i")>-1,f=i.indexOf("m")>-1,m=i.indexOf("y")>-1,x=(i=i.replace(/y/g,""),t=t instanceof RegExp?t.global?t:t.addFlags("g"):new XRegExp(t,"g"+i),
n=n instanceof RegExp?n.global?n:n.addFlags("g"):new XRegExp(n,"g"+i),[]),v=0,b=0,w=0,S=0;if(h){if(h.length>1)throw SyntaxError("can't supply more than one escape character")
;if(f)throw TypeError("can't supply escape character when using the multiline flag");o=XRegExp.escape(h),u=new RegExp("^(?:"+o+"[\\S\\s]|(?:(?!"+t.source+"|"+n.source+")[^"+o+"])+)+",d?"i":"")}for(;;){
if(t.lastIndex=n.lastIndex=w+(h?(u.exec(e.slice(w))||[""])[0].length:0),l=t.exec(e),c=n.exec(e),l&&c&&(l.index<=c.index?c=null:l=null),l||c)b=(l||c).index,w=(l?t:n).lastIndex;else if(!v)break;if(m&&!v&&b>S)break;if(l)v++||(s=b,a=w);else{
if(!c||!v)throw t.lastIndex=n.lastIndex=0,Error("subject data contains unbalanced delimiters");if(!--v&&(g?(g[0]&&s>S&&x.push([g[0],e.slice(S,s),S,s]),g[1]&&x.push([g[1],e.slice(s,a),s,a]),g[2]&&x.push([g[2],e.slice(a,b),a,b]),
g[3]&&x.push([g[3],e.slice(b,w),b,w])):x.push(e.slice(a,b)),S=w,!p))break}b===w&&w++}return p&&!m&&g&&g[0]&&e.length>S&&x.push([g[0],e.slice(S),S,e.length]),t.lastIndex=n.lastIndex=0,x};